# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"tokenizer": "01_bert.ipynb",
         "model": "01_bert.ipynb",
         "unmasker": "01_bert.ipynb",
         "spacifySeq": "01_bert.ipynb",
         "maskifySeq": "02_esm.ipynb",
         "allResidueCoordinates": "01_bert.ipynb",
         "allResiduePredictions": "00_core.ipynb",
         "getTopSeq": "00_core.ipynb",
         "residuePredictionScore": "00_core.ipynb",
         "hasNonStandardAA": "00_core.ipynb",
         "modelPredDF": "00_dataframe.ipynb",
         "aaPosDict": "01_bert.ipynb",
         "bertPredictionDF": "01_bert.ipynb",
         "batch_converter": "02_esm.ipynb",
         "naturalAAIndex": "02_esm.ipynb",
         "getNatProbs": "02_esm.ipynb",
         "esmPredictionDF": "02_esm.ipynb"}

modules = ["berteome.py",
           "berteomeDF.py",
           "prot_bert.py",
           "esm.py"]

doc_url = "https://tijeco.github.io/berteome/"

git_url = "https://github.com/tijeco/berteome/tree/{branch}/"

def custom_doc_links(name): return None
