# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"tokenizer": "00_core.ipynb",
         "model": "00_core.ipynb",
         "unmasker": "00_core.ipynb",
         "spacifySeq": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://tijeco.github.io/berteome/"

git_url = "https://github.com/tijeco/berteome/tree/{branch}/"

def custom_doc_links(name): return None
