# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"spacifySeq": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://tijeco.github.io/berteome/"

git_url = "https://github.com/tijeco/berteome/tree/{branch}/"

def custom_doc_links(name): return None
