# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/final/02_generate_sequences.ipynb.

# %% auto 0
__all__ = ['top_k_variants']

# %% ../notebooks/final/02_generate_sequences.ipynb 1
import pandas as pd

# %% ../notebooks/final/02_generate_sequences.ipynb 3
def top_k_variants(berteome, k):
  seqList = list(berteome.predDf["wt"])
  variantDict = {}
  for index, row in berteome.predDf.iterrows():
    aa_scores = row[list(berteome.aas)]
    top_k_scores = aa_scores.where(aa_scores.index != row["wt"]).sort_values(ascending=False).head(k)
    top_k_subs = list(top_k_scores.index)
    for res in top_k_subs:
      seqCopy = seqList.copy()
      seqCopy[index] = res
      variantDict[f"{index}sub{res}"] =''.join(seqCopy)
  return pd.DataFrame.from_dict(variantDict, orient = "index", columns = ["seq"]).rename_axis("sub").reset_index()

